name: Builder

on:
  push:
    branches:
      - main

jobs:
  builder:
    runs-on: macOS-13
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Import Apple Application Certificate
      uses: apple-actions/import-codesign-certs@v3
      with: 
        keychain-password: ${{ github.run_id }}
        p12-file-base64: ${{ secrets.APPLE_DEVELOPERIDAPPLICATION_B64 }}
        p12-password: ${{ secrets.APPLE_DEVELOPERIDAPPLICATION_DECRYPT }}

    - name: Import Apple Installer Certificate
      uses: apple-actions/import-codesign-certs@v3
      with:
        create-keychain: false
        keychain-password: ${{ github.run_id }}
        p12-file-base64: ${{ secrets.APPLE_DEVELOPERIDINSTALLER_B64 }}
        p12-password: ${{ secrets.APPLE_DEVELOPERIDINSTALLER_DECRYPT }}

    # - name: Prepare Keychain fun
    #   run: |
    #     xcrun notarytool store-credentials "Cockatoo" --apple-id "${{ secrets.APPLE_SIGNING_EMAIL }}" --team-id "MZ63L33DVN" --password "${{ secrets.APPLE_SIGNING_PASSWORD }}"

    - name: Make builder and output dir
      run: |
        mkdir builder
        mkdir output
    
    - name: Install dependencies 
      run: |
        brew reinstall shc autoconf automake libtool
  
    - name: Build binary
      run: |
        ls -lh
        shc -r -f cockatoo.sh -o cockatoo
        mv cockatoo builder/
        ls -lh builder

    # - name: Codesign Binary
    #   run: |
    #     codesign --deep --force --verify --verbose --sign "Developer ID Application: Michael Jon Ovcaric (MZ63L33DVN)" --timestamp -o runtime -i "gg.jonblack.cockatoo" builder/cockatoo

    # - name: Verify codesign
    #   run: |
    #     codesign --verify --verbose builder/cockatoo

    # - name: Package binary
    #   run: |
    #     pkgbuild --root builder/ --identifier gg.jonblack.cockatoo --version 0.1 --sign "Developer ID Installer: Michael Jon Ovcaric (MZ63L33DVN)" --install-location /usr/local/bin builder/cockatoo.pkg

    # - name: Notarize the PKG
    #   id: notarize
    #   run: |
    #     xcrun notarytool submit builder/cockatoo.pkg --apple-id "${{ secrets.APPLE_SIGNING_EMAIL }}" --password "${{ secrets.APPLE_SIGNING_PASSWORD }}" --team-id "MZ63L33DVN" --wait

    # - name: Staple Notarization
    #   run: |
    #     xcrun stapler staple builder/cockatoo.pkg

    # - name: Move to output dir
    #   run: |
    #     mv builder/cockatoo.pkg output/cockatoo.pkg

    - name: Release Package
      uses: actions/upload-artifact@v4.3.4
      with:
        name: Cockatoo Package
        path: builder/*