name: Builder

on:
  push:
    branches:
      - main

jobs:
  builder:
    runs-on: macOS-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Import Codesign Certificates - Application
      uses: apple-actions/import-codesign-certs@v3
      with: 
        p12-file-base64: ${{ secrets.APPLE_DEVELOPERIDAPPLICATION_B64 }}
        p12-password: ${{ secrets.APPLE_DEVELOPERIDAPPLICATION_DECRYPT }}

    - name: Make builder and output dir
      run: |
        mkdir builder
        mkdir output
    
    - name: Install dependencies 
      run: |
        brew install shc autoconf automake libtool
    
    - name: Install Quill
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/quill/main/install.sh | sh -s -- -b /usr/local/bin
  
    - name: Build
      run: |
        ls -lh
        shc -f cockatoo.sh -o builder/cockatoo
        ls -lh builder

    - name: Codesign package
      run: |
        quill sign-and-notarize builder/cockatoo

    - name: Verify codesign
      run: |
        codesign -dvvv builder/cockatoo
