name: Builder

on:
  push:
    branches:
      - main

jobs:
  builder:
    runs-on: macOS-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Import Apple Application Certificate
      uses: apple-actions/import-codesign-certs@v3
      with: 
        keychain-password: ${{ github.run_id }}
        p12-file-base64: ${{ secrets.APPLE_DEVELOPERIDAPPLICATION_B64 }}
        p12-password: ${{ secrets.APPLE_DEVELOPERIDAPPLICATION_DECRYPT }}

    - name: Import Apple Installer Certificate
      uses: apple-actions/import-codesign-certs@v3
      with:
        create-keychain: false
        keychain-password: ${{ github.run_id }}
        p12-file-base64: ${{ secrets.APPLE_DEVELOPERIDINSTALLER_B64 }}
        p12-password: ${{ secrets.APPLE_DEVELOPERIDINSTALLER_DECRYPT }}

    - name: Prepare Keychain fun
      run: |
        xcrun notarytool store-credentials "Cockatoo" --apple-id "${{ secrets.APPLE_SIGNING_EMAIL }}" --team-id "MZ63L33DVN" --password "${{ secrets.APPLE_SIGNING_PASSWORD }}"

    - name: Make builder and output dir
      run: |
        mkdir builder
        mkdir output
    
    - name: Install dependencies 
      run: |
        brew install shc autoconf automake libtool
    
    # - name: Install Quill
    #   run: |
    #     curl -sSfL https://raw.githubusercontent.com/anchore/quill/main/install.sh | sh -s -- -b /usr/local/bin
  
    - name: Build binary
      run: |
        ls -lh
        shc -f cockatoo.sh -o builder/cockatoo
        ls -lh builder

    - name: Codesign Binary
      run: |
        codesign -s "Developer ID Application: Michael Jon Ovcaric (MZ63L33DVN)" -f --timestamp -o runtime -i "gg.jonblack.cockatoo" builder/cockatoo

    - name: Verify codesign
      run: |
        codesign -dvvv builder/cockatoo

    - name: Zip binary
      run: |
        zip -r builder/cockatoo.zip builder/cockatoo

    - name: Notarization
      run: |
        xcrun notarytool submit "builder/cockatoo.zip" --keychain-profile "Cockatoo" --wait
        xcrun stapler staple "builder/cockatoo"

        mv "builder/cockatoo.zip" "output/cockatoo.zip"
